### ISSUE TITLE
regarding data used

### ISSUE THREAD

**Issue by sheth17nirali** [raffg/basic_nlp#1]
sir i was searching for your email id everywhere but didn't found. i wanted the book data you have used for deep leaning on text summarization and semantic analysis. if its possible for you can you mail me the .txt format of the books you have used so i can go through the. my emial id is nirali.sheth17@gmail.com

**Comment by ghost** [comment]
I'm sorry to ask for the same thing. This seemed like a very cool project, so i wanted to show it as an application for the students i'm teaching. Ofcourse credited to you, but i cannot recreate the graphs without the data on the same format 😓  

If you're able and willing to share the files it would be greatly appreciated. 

micael DOT austad AT gmail DOT com
